name: Publish mai.utils Package

on:
  push:
    branches:
      - main
    paths:
      - 'mai/utils/**'

jobs:
  check-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Step 3: Install dependencies for versioning and publishing
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine bump2version

      # Step 4: Check for changes in mai/utils
      - name: Check for changes in mai/utils
        id: changes
        run: |
          if git diff --quiet HEAD^ HEAD -- mai/utils/; then
            echo "No changes in mai/utils"
            exit 0
          else
            echo "Changes detected in mai/utils"
          fi

      # Step 5: Bump the version
      - name: Bump version
        id: version
        run: |
          if [ -f mai/utils/setup.py ]; then
            bump2version patch --allow-dirty --current-version $(python setup.py --version) --commit --tag
          else
            echo "setup.py not found!"
            exit 1
          fi
        working-directory: mai/utils

      # Step 6: Build the package
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
        working-directory: mai/utils

      # Step 7: Publish to PyPI
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*
        working-directory: mai/utils
